---
- hosts: weatherapp
  gather_facts: false
  become: true
  vars:
    docker_users: 
      - ubuntu
    pip_install_packages:
      - name: docker 
    pip_package: python3-pip 
    
  roles: 
   - role: geerlingguy.pip
   - role: geerlingguy.docker
  tasks:
  - import_tasks: playbook.yml
  - name: Install extra packages
    apt:
      name: 
      - git
      - net-tools
      - vim
      - python3-pip
      - python3
      state: present
    become: true
  - name: Clone Weatherapp application
    git:
      repo: https://github.com/AugustasV/weatherapp
      clone: yes
      force: yes
      dest: /home/ubuntu/weatherapp
      version: master
  - name: install docker pip
    pip:
      name: docker-compose
  - name: Run docker-compose up
    docker_service:
      project_src: /home/ubuntu/weatherapp
      build: yes
    register: output
  - debug:
        var: output
  - name: Inspect multiple images
    docker_image_facts:
      name:
        - frontend
        - backend
        - weatherapp
  - name: Curl website to check if it working
    uri:
      url: http://localhost:8000/
      method: GET
      return_content: yes
      validate_certs: no
    register: showvmstatus
  - name: Return status
    debug: var=showvmstatus
