#AWS playbook
---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: id_rsa
    region: eu-central-1
    image: ami-0b418580298265d5c 
    id: "web-app"
    sec_group: "{{ id }}-sec"
    ec2_access_key: AKIATLKSFNDFSY5KOZ4O
    ec2_secret_key: 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

  tasks:

    - name: Get instances facts
      ec2_instance_facts:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ region }}"
      register: result

    - name: Instances ID
      debug:
        msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result.instances }}"

      tags: always

    - name: Upload public key to AWS
      ec2_key:
        name: "{{ key_name }}"
        key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"

    - name: Create security group
      ec2_group:
        name: "{{ sec_group }}"
        description: "Sec group for app {{ id }}"
        # vpc_id: 12345
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        rules:
          - proto: tcp
            from_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ssh port
          - proto: tcp 
            from_port: 9000
            cidr_ip: 0.0.0.0/0
            rule_desc: frontentd
          - proto: tcp
            from port: 8000
            cidr_ip: 0.0.0.0/0
            rule_desc: web
      register: result_sec_group

    - name: Launch the new EC2 Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true 
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{count}}"
      register: ec2

      tags: ['never', 'create_ec2']
