---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: aws_id
    region: eu-central-1
    image: ami-0b418580298265d5c 
    id: "weather-app"
    instance_type: t2.micro
    sec_group: "{{ id }}-sec"
    ec2_access_key: "{{ec2_access_key}}"
    ec2_secret_key: "{{ec2_secret_key}}"
  vars_files:
    - group_vars/all/keys.yml
  tasks:
    - name: Get instances facts
      ec2_instance_info:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ region }}"
      register: result

    - name: Upload public key to AWS
      ec2_key:
        name: "{{ key_name }}"
        key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"

    - name: Create security group
      ec2_group:
        name: "{{ sec_group }}"
        description: "Sec group for app {{ id }}"
        # vpc_id: 12345
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        rules:
          - proto: tcp
            ports: 
            - 22
            - 8000
            - 9000
            cidr_ip: 0.0.0.0/0
    - name: Launch the new EC2 Instance. It can take some time.
      ec2_instance:
        name: "{{ id }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        network:
          assign_public_ip: true
        tags:
          Docker: "{{ id }}"
        image_id: "{{ image }}"
        wait: true
        region: "{{ region }}"
        key_name: "{{ key_name }}"
      register: ec2         

    - meta: refresh_inventory
- import_playbook: ansible.yml
