plugin: aws_ec2
regions:
  - eu-central-1
boto_profile: new
hostname:
  ip-address
keyed_groups:
  # add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags
  # create a group per region e.g. us_east_2
  - prefix: instance_type
    key: t2.micro
compose:
  ansible_user: "'ubuntu'"